version: '1.0'
services:
  postgres:
    image: "postgres:15.4"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defktnt8km06ra
    ports:
      - 5432:5432