/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multiplayer.chess.be.api.command

import io.micronaut.runtime.Micronaut

    fun main() {
        System.getProperties().setProperty("java.net.preferIpv4Stack","true")

        Micronaut.build().packages("multiplayer.chess.be.api.command").start()
        println("Hello homies")
    }
