/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package multiplayer.chess.be.api.command

import io.micronaut.runtime.Micronaut

object Main {
    @Suppress("MemberNameEqualsClassName")
    @JvmStatic
    fun main(args: Array<String>) {
        System.getProperties().setProperty("java.net.preferIpv4Stack","true")

        Micronaut.build().packages("multiplayer").mainClass(Main.javaClass).start()
        println("Hello homies")
    }
}
