/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multiplayer.chess.be.kotlin-library-conventions")
    id("io.micronaut.application") version "4.0.2"
}

repositories {
    mavenCentral()
}

dependencies {
    api(project(":application"))
    api("io.micronaut.data:micronaut-data-jdbc:3.10.0")
    implementation("org.postgresql:postgresql:42.6.0")
    implementation("io.micronaut:micronaut-inject-java")
    implementation("io.micronaut:micronaut-inject")
    implementation(platform("io.micronaut:micronaut-bom:3.10.1"))
    implementation("io.micronaut:micronaut-validation")
    implementation("io.micronaut.data:micronaut-data-processor:3.10.0")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation("io.micronaut.sql:micronaut-jooq")
    implementation("io.micronaut.flyway:micronaut-flyway")
    implementation("javax.persistence:javax.persistence-api:2.2")
}

